# Uncommend the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
])

languages([
  'en-US',
])

# Where should the resulting screenshots be stored?
# screenshots_path "./screenshots"

# JavaScript UIAutomation file
# js_file './snapshot.js'

# The name of the project's scheme
# scheme 'SchemeName'

# Where is your project (or workspace)? Provide the full path here
# project_path './YourProject.xcworkspace'

# By default, the latest version should be used automatically. If you want to change it, do it here
# ios_version '8.1'